### ISSUE TITLE
"locs" settings

### ISSUE THREAD

**Issue by xes** [xdarklight/drv_dsl_cpe_api_vrx#2]
Since it's very hard to understand what is actually supported by the dsl chip in use and what not, i hope you could clarify a common question that everyone asks about lantiq chips.

The "locs 0 -xx" command. 

Is this supported by the RX208? (the one installed in the TD-W8970)

Since someone says that the command gives the expected result and obtains the reduction of the SNR margin... someone else reports no effect at all.

Is this the right command?
Is it possible to enable some kind of better debug of what is happening?
Which is the meaning of the result numbers?  For example "-20"?

Any help or clarification is really appreciated.

**Comment by xdarklight** [comment]
sorry, but I don't know much about the DSL spec, I can only tell you what the source code says: https://github.com/xdarklight/dsl_cpe_control_vrx/blob/master/src/dsl_cpe_cli_access.c#L5772
The first parameter is one of the listed values (0-4, where 0 = DSL_OPT_NOISE_MARGIN_DELTA_DS) and the second parameter is the value for that setting.
This is then passed to the kernel driver: https://github.com/xdarklight/drv_dsl_cpe_api_vrx/blob/3fb0d7e68f81c4d2a1834b62a983fe9b2d60daf6/src/common/drv_dsl_cpe_api.c#L3138
...which then passes it to the DSL firmware.

result number -20 is DSL_WRN_NOT_RECOMMENDED_CONFIG (changelog says about this: `negative DSL_OPT_NOISE_MARGIN_DELTA_DS should trigger a warning (it does not).
  Special warning "DSL_WRN_NOT_RECOMMENDED_CONFIG" return added in case of
  negative values configured.`)

I suggest you write an email to the openwrt(-devel) mailing list, asking for help there.
The reason why you are not seeing a change in SNR margin may be related to the DSL spec - and as I said that is a black-box to me ;)
